### PR TITLE
DB support utf8

### PR DESCRIPTION
**Pull request by mightqxc**
With a second thought, can we first try this on one node with utf8-encoding DB connection?

### CODE REVIEW

**Comment by tmaeno** [comment]
Have you briefly tested it with INTR? If so, OK to try on a prod node.

**Comment by mightqxc** [comment]
Tested with INTR.
Now testing on atlas-pandaserver-00

**Comment by mightqxc** [comment]
The UnicodeEndocdeError was gone after the this change.

However, I found another error (not related to utf8 change though):

```
2020-08-11 08:49:42,602 panda.log.DBProxy: ERROR    updateJobStatus : failed to update CE from harvester table with Tra
ceback (most recent call last):
  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/taskbuffer/OraDBProxy.py", line 2534, in updateJobStatus
    self.cur.execute(sql_ce + comment, varMap)
  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/taskbuffer/WrappedCursor.py", line 89, in execute
    ret = cur.execute(sql, varDict)
cx_Oracle.DatabaseError: ORA-01427: single-row subquery returns more than one row
 for PanDAID 4813056464

2020-08-11 08:49:42,610 panda.log.DBProxy: ERROR    updateJobStatus : failed to update CE from harvester table with Tra
ceback (most recent call last):
  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/taskbuffer/OraDBProxy.py", line 2534, in updateJobStatus
    self.cur.execute(sql_ce + comment, varMap)
  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/taskbuffer/WrappedCursor.py", line 89, in execute
    ret = cur.execute(sql, varDict)
cx_Oracle.DatabaseError: ORA-01427: single-row subquery returns more than one row
 for PanDAID 4813091056

```
The DB records say:

```
SQL> SELECT hw.harvesterid,hw.workerid,computingelement FROM ATLAS_PANDA.harvester_workers hw, ATLAS_PANDA.Harvester_Rel_Jobs_Workers hrjw WHERE hw.workerid = hrjw.workerid AND hw.harvesterid= hrjw.harvesterid AND hrjw.pandaid = 4813056464;

HARVESTERID                                        |   WORKERID | COMPUTINGELEMENT
-------------------------------------------------- | ---------- | --------------------------------------------------------------------------------------------------------------------------------
LRZ_c2pap                                          |      44316 |
LRZ_c2pap                                          |      44312 |

SQL> SELECT hw.harvesterid,hw.workerid,computingelement FROM ATLAS_PANDA.harvester_workers hw, ATLAS_PANDA.Harvester_Rel_Jobs_Workers hrjw WHERE hw.workerid = hrjw.workerid AND hw.harvesterid= hrjw.harvesterid AND hrjw.pandaid = 4813091056;

HARVESTERID                                        |   WORKERID | COMPUTINGELEMENT
-------------------------------------------------- | ---------- | --------------------------------------------------------------------------------------------------------------------------------
LRZ_c2pap                                          |      44317 |
LRZ_c2pap                                          |      44313 |

```
so some jobs map to multiple harvester workers. Not sure if this is allowed (say 1-to-many maptype?).

Also I have no idea how to fix since the subquery is for UPDATE SET

```
sql_ce = """
                                     UPDATE ATLAS_PANDA.jobsActive4
                                     SET computingelement = (SELECT computingelement FROM ATLAS_PANDA.harvester_workers hw, ATLAS_PANDA.Harvester_Rel_Jobs_Workers hrjw
                                                             WHERE hw.workerid = hrjw.workerid AND hw.harvesterid = hrjw.harvesterid AND hrjw.pandaid = :PandaID)
                                     where PandaID=:PandaID
                                     """
```

**Comment by tmaeno** [comment]
I've fixed the CE issue in the git repo.

**Comment by mightqxc** [comment]
Thanks. Then can we merge this?

**Comment by tmaeno** [comment]
OK.

**Pull request merged**
