### PR TITLE
fix to activate esmerge jobs

### PR DESCRIPTION
**Pull request by wguanicedew**
fix to activate es merge jobs.

### CODE REVIEW

**Comment by tmaeno** [comment]
It is rather intentional to keep the original job status to avoid adding output files to wrong _sub datasets etc which cause problems to downstream tasks. The proper fix is to kill merge jobs in defined state without retry in panda and let JEDI to make a new merge job, which should be OK since events are not discarded.

**Comment by wguanicedew** [comment]
because the current esmerge job is defined status, will the new merge job be in defined status again if copying the original job status?

**Comment by tmaeno** [comment]
Timeout for defined is 4h. It will be retried a couple times in defined and be passed to JEDI to make a correct merge job which will go to activated. If you manually activate those jobs something wrong may happen since the original jobs didn't go through the DDM procedure correctly.

BTW, have you checked why the original jobs were in defined state which is not normal?

**Comment by wguanicedew** [comment]
Hi,
Yes. I checked why the esmerge job was in defined status.
1) jedi creates a retry jobset with 5 consumers (all events are already done by jobsets before it). These 5 consumers are in defined status.
2) ppEventService checks these 5 consumers, found there are no left events. Then ppEventService will close 4 consumers.
3) for the last consumer, ppEventService found there are no left events and there are no left consumers, ppEventService creates the esmerge jobs and copies the jobstatus from the last consumer which is defined.

**Comment by tmaeno** [comment]
In the first place

> jedi creates a retry jobset with 5 consumers (all events are already done by jobsets before it). 
> These 5 consumers are in defined status.

this should not happen since a merge job is directly created from those consumers and they immediately go to closed in this case, which implies that the process to generate merge jobs in panda didn't run properly. I suggest that you investigate why the merge job was not generated immediately. 

In any case, the proposed fix is irrelevant. Those jobs should be killed without being sent to WNs and panda is doing so although there are redundant retries.

**Pull request closed without merging**
